// index: generate packages/<pkg>/README.md, the lemma index people and AI agents search.
// usage: bun tools/mathlib/index.ts <pkgdir> <name> <version> [--check] [--stdout]

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { PkgError, ROOT, packageModules, parseModule, readLock } from "./lib.ts";

const USAGE = "usage: bun tools/mathlib/index.ts <pkgdir> <name> <version> [--check] [--stdout]";
const usage = (msg: string): never => { console.error(`index: ${msg}\n${USAGE}`); process.exit(2); };

const [dirArg, name, version] = process.argv.slice(2).filter((a) => !a.startsWith("--"));
if (!dirArg || !name || !version) usage("need <pkgdir> <name> <version>");
if (!/^\d+\.\d+\.\d+\.\d+$/.test(version)) usage(`version must be a.b.c.d, got ${JSON.stringify(version)}`);
const dir = resolve(dirArg);
const alias = (m: string) => "M" + m[0].toUpperCase() + m.slice(1);
const cell = (s: string) => "`" + s.replace(/\|/g, "\\|") + "`";

// The lock records the version that first published each entry; absent or null means unreleased.
const lockFile = join(dir, "PUBLIC_API.lock");
const lock = readLock(lockFile);
let hasNext = false;
const sinceCell = (module: string, entry: string) => {
  const since = lock[`${module}.${entry}`]?.since ?? null;
  if (since === null) hasNext = true;
  return since ?? "next";
};

const head: string[] = [
  `# ${name}`,
  "",
  `Machine-checked lemmas for Bend 2, checked with \`bend ${JSON.parse(readFileSync(join(ROOT, "toolchain.json"), "utf8")).bend.version}\`.`,
  "",
  "Rewriting: `%e : P` replaces the right side of `e` with its left side, so `name` expands the simple",
  "side into the compound one and `name_sym` simplifies the compound side.",
  "",
];
const body: string[] = [];
let total = 0;
let files: string[];
try { files = packageModules(dir); } catch (e) { if (e instanceof PkgError) usage(e.message); throw e; }
for (const file of files) {
  const m = parseModule(file);
  const laws = m.laws.filter((l) => !l.name.startsWith("internal_"));
  const preds = m.defs.filter((d) => !d.name.startsWith("internal_") && /->\s*(Data|Type)\s*:\s*$/.test(d.header));
  if (laws.length + preds.length === 0) continue;
  total += laws.length;
  const rel = relative(dir, file).replace(/\.bend$/, "");
  body.push(`## ${m.name}`, "", "```python", `import ${name}@${version}/${rel}.bend as ${alias(m.name)}`, "```", "");
  if (preds.length) {
    body.push("| predicate | definition | since |", "|---|---|---|");
    for (const p of preds) body.push(`| ${cell(p.header.replace(/^def\s+/, "").replace(/:\s*$/, ""))} | ${cell(p.body.map((l) => l.trim()).join(" "))} | ${sinceCell(m.name, p.name)} |`);
    body.push("");
  }
  body.push("| lemma | statement | meaning | since |", "|---|---|---|---|");
  for (const l of laws) {
    const binders = l.binders.map((b) => `${b.mark}${b.name}: ${b.type}`).join(", ");
    body.push(`| ${cell(`${l.name}(${l.binders.map((b) => (b.mark === "~" ? "~" : "") + b.name).join(", ")})`)} | ${cell(`${binders ? `∀ ${binders}. ` : ""}${l.claimLines[0]}`)} | ${(l.doc[0] ?? "").replace(/\|/g, "\\|")} | ${sinceCell(m.name, l.name)} |`);
  }
  body.push("");
}
const out = [...head];
if (hasNext) out.push("Rows marked `next` are proved in this repository but not yet published: the import lines above do not contain them yet.", "");
out.push(...body, `${total} lemmas. Generated by \`tools/mathlib/index.ts\`.`, "");
const target = join(dir, "README.md");
const text = out.join("\n");
if (process.argv.includes("--check")) {
  const same = existsSync(target) && readFileSync(target, "utf8") === text;
  console.log(same ? "index up to date" : `stale: ${target}`);
  process.exit(same ? 0 : 1);
}
if (process.argv.includes("--stdout")) { process.stdout.write(text); process.exit(0); }
writeFileSync(target, text);
console.log(`wrote ${target} (${total} lemmas)`);
