// index: generate packages/<pkg>/README.md, the lemma index people and AI agents search.
// usage: bun tools/mathlib/index.ts <pkgdir> <name> <version> [--check]

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { packageModules, parseModule } from "./lib.ts";

const [dirArg, name, version] = process.argv.slice(2).filter((a) => !a.startsWith("--"));
if (!dirArg || !name || !version) { console.error("usage: index.ts <pkgdir> <name> <version> [--check]"); process.exit(2); }
const dir = resolve(dirArg);
const alias = (m: string) => "M" + m[0].toUpperCase() + m.slice(1);
const cell = (s: string) => "`" + s.replace(/\|/g, "\\|") + "`";

const out: string[] = [
  `# ${name}`,
  "",
  `Machine-checked lemmas for Bend 2, checked with \`bend ${JSON.parse(readFileSync(join(dir, "..", "..", "toolchain.json"), "utf8")).bend.version}\`.`,
  "Not related to the hub package `bend-math-lib`.",
  "",
  "Rewriting: `%e : P` replaces the right side of `e` with its left side, so `name` expands the simple",
  "side into the compound one and `name_sym` simplifies the compound side.",
  "",
];
let total = 0;
for (const file of packageModules(dir)) {
  const m = parseModule(file);
  const laws = m.laws.filter((l) => !l.name.startsWith("internal_"));
  const preds = m.defs.filter((d) => !d.name.startsWith("internal_") && /->\s*(Data|Type)\s*:\s*$/.test(d.header));
  if (laws.length + preds.length === 0) continue;
  total += laws.length;
  out.push(`## ${m.name}`, "", "```python", `import ${name}@${version}/${m.name}.bend as ${alias(m.name)}`, "```", "");
  if (preds.length) {
    out.push("| predicate | definition |", "|---|---|");
    for (const p of preds) out.push(`| ${cell(p.header.replace(/^def\s+/, "").replace(/:\s*$/, ""))} | ${cell(p.body.map((l) => l.trim()).join(" "))} |`);
    out.push("");
  }
  out.push("| lemma | statement | meaning |", "|---|---|---|");
  for (const l of laws) {
    const binders = l.binders.map((b) => `${b.mark}${b.name}: ${b.type}`).join(", ");
    out.push(`| ${cell(`${l.name}(${l.binders.map((b) => (b.mark === "~" ? "~" : "") + b.name).join(", ")})`)} | ${cell(`${binders ? `∀ ${binders}. ` : ""}${l.claimLines[0]}`)} | ${(l.doc[0] ?? "").replace(/\|/g, "\\|")} |`);
  }
  out.push("");
}
out.push(`${total} lemmas. Generated by \`tools/mathlib/index.ts\`.`, "");
const target = join(dir, "README.md");
const text = out.join("\n");
if (process.argv.includes("--check")) {
  const same = existsSync(target) && readFileSync(target, "utf8") === text;
  console.log(same ? "index up to date" : `stale: ${target}`);
  process.exit(same ? 0 : 1);
}
writeFileSync(target, text);
console.log(`wrote ${target} (${total} lemmas)`);
